# Copyright 2018 César Sahagún License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0
{
    "name": "sercone",
    "version": "1.0.0.0.0",
    "author": "César",
    "website": "https://cesar.com",
    "license": "AGPL-3",
    "depends": [
                "l10n_es",
                "l10n_es_account_asset",
                "l10n_es_account_bank_statement_import_n43",
                "l10n_es_account_banking_sepa_fsdd",
                "l10n_es_account_invoice_sequence",
                "l10n_es_aeat_mod111",
                "l10n_es_aeat_mod115",
                "l10n_es_aeat_mod123",
                "l10n_es_aeat_mod303",
                "l10n_es_aeat_mod349",
                "l10n_es_aeat_sii",
                "l10n_es_dua",
                "l10n_es_facturae",
                "l10n_es_vat_book",
                "l10n_es_mis_report",
                "l10n_es_partner",
                "l10n_es_partner_mercantil",
                "l10n_es_toponyms",
                "account_banking_sepa_credit_transfer",
                "account_cancel",
                "account_cash_invoice",
                "account_due_list_payment_mode",
                "account_financial_report",
                "account_fiscal_year",
                "account_group_menu",
                "account_invoice_inter_company",
                "account_invoice_constraint_chronology",
                "account_invoice_force_number",
                "account_invoice_supplier_ref_unique",
                "account_move_line_tax_editable",
                "account_multicompany_easy_creation",
                "account_partner_reconcile",
                "account_payment_return_import_sepa_pain",
                "account_reversal",
                "auditlog",
                "backend_theme_v11",
                "base_technical_features",
                "base_user_role",
                "contacts",
                "contract",
                "disable_odoo_online",
                "drag-and-drop",
                "mass_editing",
                "partner_contact_in_several_companies",
                "phone_validation",
                "res_config_settings_enterprise_remove",
                "web_action_conditionable",
                "web_decimal_numpad_dot",
                "web_dialog_size",
                "web_environment_ribbon",
                "web_favicon",
                "web_listview_range_select",
                "web_no_bubble",
                "web_notify",
                "web_sheet_full_width",
                "web_searchbar_full_width",
                "web_widget_x2many_2d_matrix",
                "web_timeline",
                "web_tree_many2one_clickable",
                "web_widget_many2many_tags_multi_selection",
    ],
    "installable": True,
}

